language: python

sudo: enabled


before_script:
  - psql -c 'create database pytestponyorm;' -U postgres
  - psql -c "CREATE USER j WITH PASSWORD 'j;'" -U postgres
  - psql -c "GRANT ALL ON DATABASE pytestponyorm TO j;"

matrix:
    include:
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.6
        env: TOX_ENV=flake8

branches:
  only:
  - master

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
