language: python

sudo: enabled


before_script:
  - psql -c 'create database pytestponyorm;' -U postgres
  - psql -c "CREATE USER j WITH PASSWORD 'j;'" -U postgres
  - psql -c "GRANT ALL ON DATABASE pytestponyorm TO j;" -U postgres

branches:
  only:
  - master
  - dev

install:
  - pip install tox-travis

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
